### ISSUE TITLE
Apakah bisa portal jabar digunakan untuk proyek turunan lainnya?

### ISSUE THREAD

**Issue by vzrenggamani** [jabardigitalservice/portal-jabar-services#204]
Apakah proyek portal-jabar-* dapat digunakan untuk proyek turunan lainnya oleh masyarakat umum? jika demikian apakah ada panduan pemasangan dari ketiga layanan baik frontend, cms, dan servicesnya?

**Comment by adzharamrullah** [comment]
Hallo mas @vzrenggamani perkenalkan nama saya Adzhar Amrullah saya di Jabar Digital Service sebagai Engineering Manager, kebetulan saya yang bertanggung jawab atas produk ini dari sisi Engineering. Untuk saat ini produk Integrated Portal Jabar (IPJ) masih dalam proses development dan kami belum bisa memastikan ini bisa digunakan oleh publik, kami sangat terbuka untuk diskusi dan komunikasi lebih lanjut dengan mas @vzrenggamani mengenai kebutuhan rincinya seperti apa?. Apabila berkenan mas @vzrenggamani boleh mengiriman purpose melalui kanal email kami di digital.service@jabarprov.go.id. Hatur nuhun

**Comment by vzrenggamani** [comment]
Halo mas @adzharamrullah, kebetulan saya sedikit tertarik untuk mencoba mendeploy IPJ ini di server pribadi saya karena interest dengan arsitektur portanya. Sayangnya di repos ini instruksi deployment di local belum ada dengan baik jadinya saya coba tanya ke sini hehe, siapa tahu saya interest to submit PR ke proyek open-source ini seperti di KawalCovid/WBW..

**Comment by adzharamrullah** [comment]
@vzrenggamani untuk kontribusi di project repository ini kondisinya saat ini masih belum memungkinkan untuk komunitas external (public contributor) saat ini masih di develop oleh teman - teman internal Jabar Digital Service menyesuaikan timeline/milestone di internal, untuk di kontribusi oleh publik tim kami sedang mempersiapkan hal itu akan tetapi kami harus mengurus beberapa hal agar project ini bisa di kontribusi oleh publik, apabila kami sudah menyelesaikan itu kami akan umumkan hal itu dan melengkapi dokumentasinya. Terima kasih banyak mas @vzrenggamani telah tertarik dan menanyakan hal itu kepada kami.

**Comment by vzrenggamani** [comment]
Wah glad to hear that mas @adzharamrullah, in the mean time i hope this projects gonna be publicy available for external contributors. Anyway, mungkin ini saya masih cari cara buat run core servicenya wkwkw
