### ISSUE TITLE
Sebaiknya backend adalah timezone neutral (UTC)

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/portal-jabar-services#8]
https://github.com/jabardigitalservice/portal-jabar-api/blob/52d564e145456393b9fe7e0fe145a1a8eabf1104/app/main.go#L44

Backend service sebaiknya dibuat bekerja dalam konfigurasi timezone UTC yang netral. Karena backend bisa dideploy server mana saja di seluruh dunia, dan konfigurasinya sama = UTC. 

Timezone "Asia/Jakarta" adalah sudut pandang user pengguna. Bagaimana sistem jika perlu handle user dari wilayah Bali (WITA)? Penanganannya cukup ditaruh di frontend/client side, tidak di backend.

**Comment by rachadiannovansyah** [comment]
it's been done since last year mas [here](https://github.com/jabardigitalservice/portal-jabar-services/pull/31/files#diff-7725ad33515b27bed3e80eaaf13037f0d0686e97a5b85bea1095d2e3b5b9b877L42-L46:~:text=%22%25s%3F%25s-,%22,-%2C%20connection%2C)
